/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuoyRouteImport } from './routes/buoy'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MiniappsRouteImport } from './routes/miniapps'
import { Route as NewsRouteImport } from './routes/news'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TokenRouteImport } from './routes/token'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as MiniappsIndexRouteImport } from './routes/miniapps.index'
import { Route as MiniappsSlugRouteImport } from './routes/miniapps.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuoyRoute = BuoyRouteImport.update({
  id: '/buoy',
  path: '/buoy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniappsRoute = MiniappsRouteImport.update({
  id: '/miniapps',
  path: '/miniapps',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatRoute,
} as any)
const MiniappsIndexRoute = MiniappsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiniappsRoute,
} as any)
const MiniappsSlugRoute = MiniappsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MiniappsRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRoute
  '/buoy': typeof BuoyRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/explore': typeof ExploreRoute
  '/governance': typeof GovernanceRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/miniapps': typeof MiniappsRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/register': typeof RegisterRoute
  '/token': typeof TokenRoute
  '/waitlist': typeof WaitlistRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/chat/$id': typeof ChatIdRoute
  '/miniapps/$slug': typeof MiniappsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/miniapps/': typeof MiniappsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/buoy': typeof BuoyRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/explore': typeof ExploreRoute
  '/governance': typeof GovernanceRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/register': typeof RegisterRoute
  '/token': typeof TokenRoute
  '/waitlist': typeof WaitlistRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/chat/$id': typeof ChatIdRoute
  '/miniapps/$slug': typeof MiniappsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/academy': typeof AcademyIndexRoute
  '/chat': typeof ChatIndexRoute
  '/miniapps': typeof MiniappsIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRoute
  '/buoy': typeof BuoyRoute
  '/chat': typeof ChatRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/explore': typeof ExploreRoute
  '/governance': typeof GovernanceRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/miniapps': typeof MiniappsRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/register': typeof RegisterRoute
  '/token': typeof TokenRoute
  '/waitlist': typeof WaitlistRoute
  '/academy/$slug': typeof AcademySlugRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/chat/$id': typeof ChatIdRoute
  '/miniapps/$slug': typeof MiniappsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/miniapps/': typeof MiniappsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/buoy'
    | '/chat'
    | '/dashboard'
    | '/developers'
    | '/explore'
    | '/governance'
    | '/login'
    | '/marketplace'
    | '/miniapps'
    | '/news'
    | '/register'
    | '/token'
    | '/waitlist'
    | '/academy/$slug'
    | '/agents/$slug'
    | '/chat/$id'
    | '/miniapps/$slug'
    | '/news/$slug'
    | '/academy/'
    | '/chat/'
    | '/miniapps/'
    | '/news/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/buoy'
    | '/dashboard'
    | '/developers'
    | '/explore'
    | '/governance'
    | '/login'
    | '/marketplace'
    | '/register'
    | '/token'
    | '/waitlist'
    | '/academy/$slug'
    | '/agents/$slug'
    | '/chat/$id'
    | '/miniapps/$slug'
    | '/news/$slug'
    | '/academy'
    | '/chat'
    | '/miniapps'
    | '/news'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/buoy'
    | '/chat'
    | '/dashboard'
    | '/developers'
    | '/explore'
    | '/governance'
    | '/login'
    | '/marketplace'
    | '/miniapps'
    | '/news'
    | '/register'
    | '/token'
    | '/waitlist'
    | '/academy/$slug'
    | '/agents/$slug'
    | '/chat/$id'
    | '/miniapps/$slug'
    | '/news/$slug'
    | '/academy/'
    | '/chat/'
    | '/miniapps/'
    | '/news/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AdminRoute: typeof AdminRoute
  BuoyRoute: typeof BuoyRoute
  ChatRoute: typeof ChatRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  ExploreRoute: typeof ExploreRoute
  GovernanceRoute: typeof GovernanceRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MiniappsRoute: typeof MiniappsRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  TokenRoute: typeof TokenRoute
  WaitlistRoute: typeof WaitlistRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buoy': {
      id: '/buoy'
      path: '/buoy'
      fullPath: '/buoy'
      preLoaderRoute: typeof BuoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miniapps': {
      id: '/miniapps'
      path: '/miniapps'
      fullPath: '/miniapps'
      preLoaderRoute: typeof MiniappsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/miniapps/': {
      id: '/miniapps/'
      path: '/'
      fullPath: '/miniapps/'
      preLoaderRoute: typeof MiniappsIndexRouteImport
      parentRoute: typeof MiniappsRoute
    }
    '/miniapps/$slug': {
      id: '/miniapps/$slug'
      path: '/$slug'
      fullPath: '/miniapps/$slug'
      preLoaderRoute: typeof MiniappsSlugRouteImport
      parentRoute: typeof MiniappsRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcademyRouteChildren {
  AcademySlugRoute: typeof AcademySlugRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademySlugRoute: AcademySlugRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface ChatRouteChildren {
  ChatIdRoute: typeof ChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIdRoute: ChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface MiniappsRouteChildren {
  MiniappsSlugRoute: typeof MiniappsSlugRoute
  MiniappsIndexRoute: typeof MiniappsIndexRoute
}

const MiniappsRouteChildren: MiniappsRouteChildren = {
  MiniappsSlugRoute: MiniappsSlugRoute,
  MiniappsIndexRoute: MiniappsIndexRoute,
}

const MiniappsRouteWithChildren = MiniappsRoute._addFileChildren(
  MiniappsRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AdminRoute: AdminRoute,
  BuoyRoute: BuoyRoute,
  ChatRoute: ChatRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  ExploreRoute: ExploreRoute,
  GovernanceRoute: GovernanceRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MiniappsRoute: MiniappsRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  TokenRoute: TokenRoute,
  WaitlistRoute: WaitlistRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
